version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres@db/git_analytics_development
      REDIS_URL: redis://localhost:6379/0
      RAILS_ENV: development
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: git_analytics_development
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis:/data
volumes:
  postgres:
  redis:
